### ISSUE TITLE
Links are not formatted correctly for some users

### ISSUE THREAD

**Issue by fcwill** [fchat-pidgin/fchat-pidgin#120]
Posting this issue for a user:
Pidgin does not render some links correctly:
 * Normal [url]Link[/url] works as expected
 * [url=http://google.com]Google[/url] renders as follows:
![image](https://cloud.githubusercontent.com/assets/8559189/16295674/779e1180-3928-11e6-92b4-523ad3e533df.png) (e.g. instead of simply rendering a link with "Google" as text, it renders "Google (http://google.com)")
 * [channel] and [session] work similarly, producing output like "(Channel) Pidgin (flistc://XXXXX/ADH-1509b63f1b1a98c79ab9)" with no clickable parts.
 * [user] and [icon] work as expected

OS: Windows 7
Pidgin 2.11.0
F-Chat 0.5.0 (v0.5.0-130-g57da9ce)
No special plugins activated
No output in debug window related to this issue either

**Comment by syldrathecat** [comment]
This is caused by the "Conversation Colours" plugin that comes with pidgin. The flistc:// URLs are not linkified due to Pidgin/libpurple's dodgy link handling.

I don't think there's anything that can be done in the plugin to fix this.

**Comment by syldrathecat** [comment]
Above checkbox solved the user's issue ^-^
