### ISSUE TITLE
Not showing as an available account type in Bitlbee

### ISSUE THREAD

**Issue by rodneyrod** [fchat-pidgin/fchat-pidgin#126]
Tested on Ubuntu Server 14.04, using BitlBee-LIBPURPLE 3.4.2+20160708+master+46-gf60dc5c-git

Installed as follows:
1. wget the flist.so file
2. Copy file to /usr/lib/purple-2
3. Restart Bitlbee
4. Type 'help purple' in the Bitlbee console, accounts are listed but F-List isn't shown as a valid account type

libjson-glib-1.0-0 and libjson-glib-1.0-common are already installed.

Any resolution to this would be greatly appreciated.

**Comment by syldrathecat** [comment]
The release downloads are for Pidgin only, not other libpurple clients. You should try build the plugin yourself with `make FLIST_PURPLE_ONLY=1`.

**Comment by rodneyrod** [comment]
That did the trick, if you like I can try and make a pull request updating the README with this info.

**Comment by fcwill** [comment]
Sure thing, send us a PR! :)

**Comment by fcwill** [comment]
Wait ... it's already in there! Under "Build options"

**Comment by rodneyrod** [comment]
So it is, all good then.
