### ISSUE TITLE
Special characters in user info can cause a crash

### ISSUE THREAD

**Issue by fcwill** [fchat-pidgin/fchat-pidgin#127]
There are special characters (like "`💖`") in a character's info that cause Pidgin to crash.

Steps to reproduce:
Edit your character to contain one of these symbols in its info (e.g. Eye color)
Right click this character in Pidgin and select Info
Enjoy the crash

**Comment by fcwill** [comment]
Got another report of this crash happening - is this a new bug?

**Comment by vobe** [comment]
Could not reproduce on Linux. Windows-only GTK bug ?

**Comment by fcwill** [comment]
Yes, it's Windows only.

**Comment by vobe** [comment]
This bug is actually caused by libjson-glib. Using Eion Robb's build (https://eion.robbmob.com/libjson-glib-1.0.dll) avoids it, so I'm probably going to package it in the next release
