### ISSUE TITLE
Do not automatically try to re-login if kicked out

### ISSUE THREAD

**Issue by LurkerHub** [fchat-pidgin/fchat-pidgin#130]
Observed behavior:
1. Login from computer1
2. Leave without logging out, travel
3. Login from computer2
4. computer1 is kicked out, but detects it and automatically re-logins
5. computer2 is kicked out, but detects it and automatically re-logins
6. goto 4.

Expected/desired behavior:
1. Login from computer1
2. Leave without logging out, travel
3. Login from computer2
4. computer1 is kicked out, displays a "reconnect" button (same as YIM)
5. computer2 is remains logged in, user experiences bliss.

Yes, this situation is observed in the wild.  I forgot to log off from the computer at work (after work hours :) ) and cannot use the chat from home because of the behavior described above.

Problem #2: The popup telling me that I was "disconnected because the character has been logged in at another location" does not linger, but disappears after a second or less.  I had to try hitting PrintScreen several times when it popped in and out until I managed to time it right and could read what it said.  This may or may not be an artifact of the re-login attempts.

**Comment by LurkerHub** [comment]
Also saw an assertion in the debug window, probably related.

(23:21:53) util: parsed 5873
(23:21:53) flist: Received icon. (URL: https://static.f-list.net/images/avatar/my%20charcter.png) (Convo: none)
(23:21:53) flist: Processing message... (Code: VAR)
(23:21:53) flist: Processing message... (Code: VAR)
(23:21:53) flist: Processing message... (Code: VAR)
(23:21:53) flist: Processing message... (Code: VAR)
(23:21:53) flist: Processing message... (Code: VAR)
(23:21:53) flist: Processing message... (Code: VAR)
(23:21:53) flist: Processing message... (Code: HLO)
(23:21:53) flist: Processing message... (Code: CON)
(23:21:53) flist: Processing message... (Code: FRL)
(23:21:53) flist: Processing message... (Code: IGN)
(23:21:53) flist: Processing message... (Code: ADL)
(23:21:53) g_log: purple_prpl_got_account_actions: assertion `purple_account_is_connected(account)' failed
(23:21:53) flist: Processing message... (Code: LIS)
(23:21:53) flist: Processing message... (Code: LIS)
(23:21:53) flist: Processing message... (Code: LIS)
(23:21:53) flist: Processing message... (Code: LIS)
(23:21:53) flist: Processing message... (Code: LIS)
(23:21:53) flist: Processing message... (Code: LIS)
(23:21:53) flist: Processing message... (Code: LIS)
(23:21:53) flist: Processing message... (Code: LIS)
(23:21:53) flist: Processing message... (Code: LIS)
(23:21:53) flist: Processing message... (Code: LIS)
(23:21:53) flist: Processing message... (Code: LIS)
(23:21:53) flist: Processing message... (Code: LIS)

**Comment by LurkerHub** [comment]
Wow, that was quick!  Thank you!
Can you suggest when the new release is coming?

**Comment by fcwill** [comment]
We can't say yet, but it might be a while. If you can't wait, you can still use nightly builds from here: http://beam.to/fchat-pidgin - it might take a while until the most recent commits are built, though, you can try tomorrow.
/version should say `You are running Pidgin F-Chat 0.6.0 (v0.6.0-7-gf84fdc1).`
