### ISSUE TITLE
Linux 0.6.0 release download built against wrong Pidgin ABI

### ISSUE THREAD

**Issue by syldrathecat** [fchat-pidgin/fchat-pidgin#132]
The Linux release of 0.6.0 is built against Pidgin 2.11, which was unintended and does not match the Windows release, which was built against Pidgin 2.10. As a result it silently fails to load on Pidgin 2.10, which is the latest version available in most distros.

**Comment by vobe** [comment]
I think it's hopeless to try to offer a pre-build linux binary. We should use a service like OBS to automatically build packages for the most usual ones (Ubuntu, Fedora), that will guarantee that we always target the right versions for each distro

**Comment by vobe** [comment]
Fixed for a majority of users through PPA builds
