### ISSUE TITLE
Banlist does not refresh properly

### ISSUE THREAD

**Issue by narod** [fchat-pidgin/fchat-pidgin#133]
Displaying the banlist for a channel seems to display a cached(?) list instead of fetching the current one.

Manually unbanning a user or displaying the banlist a second time seem to be workarounds.

**Comment by vobe** [comment]
Are you talking about the /banlist command or something else ? There is no caching in the plugin when it comes to the /banlist command, the response you see comes straight from the F-chat server.

**Comment by vobe** [comment]
This is most likely a F-Chat server issue
