### ISSUE TITLE
Cannot connect to account using Bitlbee

### ISSUE THREAD

**Issue by rodneyrod** [fchat-pidgin/fchat-pidgin#135]
Haven't built on my machine with the debug flags so I haven't been able to get more thorough logs, however this can be reproduced by completing the following:

1. Install bitlbee-libpurple on Ubuntu Server 14.04 via the daily package repository
2. Compile and 'make install' fchat-pidgin
3. Add account in bitlbee by inputting 'acc add flist [username] [password]'
4. The following output is recorded in the bitlbee console:

> <root> flist - Logging in: Requesting login ticket
> <root> flist - Logging in: Connecting to F-Chat server
> <root> flist - Logging in: Sending WebSocket handshake
> <root> flist - Logging in: Identifying
> <root> flist - Login error: Syntax error.
> <root> flist - Logging in: Signing off..
> <root> flist - Logging in: Reconnecting in 5 seconds..

All default settings were used and no other information is provided by the output.
This has been tried with the latest package available for Ubuntu 14.04, which at the time of writing is BitlBee-LIBPURPLE 3.4.2+20160808+master+51-g88cde4e-git.

**Comment by syldrathecat** [comment]
You need to use your username and a character name separated by a colon, i.e:

    account add flist "username:Character Name" password

Does that help?

**Comment by rodneyrod** [comment]
Thank you so much for that. It was asking for 3 fields, but I was wondering why [uname] [charname] [password] with spaces wasn't working.

Again, if it's in the docs, sorry I missed it.
