### ISSUE TITLE
Static.f-list.com certificate outdated.

### ISSUE THREAD

**Issue by Kradre** [fchat-pidgin/fchat-pidgin#136]
After 13th of August pidgin begin showing that certificate of "static.f-list.com" is outdated. Plus, it was showing that it was expired in 2014.

I generated self-signed certificate, replaced it with static.f-list.com one, but when i reconnected to server, it replaced with outdated one again.

Image of certificate info: http://i.imgur.com/PX1tIJJ.png

**Comment by syldrathecat** [comment]
static.f-list.net uses certificates from cloudflare. That certificate screenshotted is not only two years old but is completely generic and not even generated for static.f-list.net. If that's what you get given when visiting https://static.f-list.net/ then someone/something is probably trying to spy on you.

Pidgin does keep a copy of certificates (.purple/certificates/x509/tls_peers/static.f-list,net) but it only makes use of them in cases where they're not signed by a valid third-party, for the user to manually verify, and replacing it will just prompt you that the certificates don't match.

**Comment by vobe** [comment]
It looks like you're infected by a trojan that's eavesdropping on your network connections.

http://news.softpedia.com/news/Dyre-Trojan-Uses-Its-Own-SSL-Certificate-to-Communicate-with-Control-Server-460224.shtml

**Comment by Kradre** [comment]
Checked whole system with Kaspersky, loaded from Linux - still same error.

Upd. Strange - it going over whole my lan. I tried it on one of my computers and it worked perfectly.
After few hours, it got same certificate error.

**Comment by vobe** [comment]
Maybe the issue is affecting your network gateway too ?

**Comment by vobe** [comment]
Thank for the update

**Comment by Kradre** [comment]
Upd 3. : It begin again replacing it, even through google dns,
Used VPN - it worked perfectly. Strange thing.
