### ISSUE TITLE
certificate errors

### ISSUE THREAD

**Issue by alexolog** [fchat-pidgin/fchat-pidgin#137]
I am getting bombarded with invalid certificate dialogs.  I accept the certificate, then after a couple of minutes it complains again.

The certificate shows:
```
Certificate Information
Common name: ssl255860.cloudflaressl.com
Issued By: CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
Fingerprint (SHA1): 40:d6:fa:e3:40:d7:09:d0:fc:79:0c:9e:c0:3a:15:40:06:55:c2:87
Activation date: Tue Jun 21 20:00:00 2016
Expiration date: Sun Dec 25 18:59:59 2016
```
Checking the issuer shows: "Unable to find Issuer Certificate"

**Comment by vobe** [comment]
Hi, what version of Pidgin are you running ? This could be caused by a root certificate being missing, I would suggest upgrading to the latest version (2.11.0)

**Comment by alexolog** [comment]
Pidgin 2.11.0 (libpurple 2.11.0)
f02ebb71b5e32cc4af521e7f89c34dedff8d09ae

Where do I get the root certificate from?

**Comment by vobe** [comment]
The root certificate you're missing is either this one
https://www.tbs-certificates.co.uk/FAQ/en/COMODO_ECC_CA.html

Or maybe this one :
https://www.tbs-certificates.co.uk/FAQ/en/COMODOECCDomainValidationSecureServerCA.html

Try downloading them and storing them in pidgin's ca-certs folder (they might need to be renamed to a .pem extension like the other files in that directory)

**Comment by alexolog** [comment]
The problem disappeared by itself, just as it appeared.

Incidentally, Looking in the debug window I noticed that the protocol seems to be extremely chatty, often processing several messages per second

**Comment by vobe** [comment]
Those messages are probably NLN, FLN and STA commands from the server. They're sent everytime a user connects, disconnects, or changes their status, regardless of your relashionship with that user. So yes, on a channel with 3000+ people, this gets a bit noisy, but that is how the protocol works. You'll find more information here : https://wiki.f-list.net/F-Chat_Server_Commands#FLN
