### ISSUE TITLE
Bottle spinning doesn't work

### ISSUE THREAD

**Issue by alexolog** [fchat-pidgin/fchat-pidgin#144]
Whenever I try to `/roll bottle` I get an error dialog saying "You spin the bottle, but nobody came."

**Comment by vobe** [comment]
The bottle command does not do much plugin-side, this error probably happened because noone in your channel was available. I could not reproduce the issue on a channel with one available person for the bottle to land on

**Comment by alexolog** [comment]
I just tried it in the public "Fantasy" channel that had 372 people in it, with the same results.
Yesterday I tried it in another channel which had tens of people with the "looking" icon.

**Comment by vobe** [comment]
I cannot roll dice on the Fantasy channel on the normal web interface either

**Comment by alexolog** [comment]
I can roll dice but not the bottle.
Can you suggest a channel that works?

**Comment by vobe** [comment]
Any private channel should do the trick. I have no idea why /bottle does not work in public channels, maybe abuse.

**Comment by alexolog** [comment]
F-list support channel confirmed that the functionality is disabled on public channels.
The error message could be less confusing though.
