### ISSUE TITLE
Commands in Bitlbee

### ISSUE THREAD

**Issue by Ceralor** [fchat-pidgin/fchat-pidgin#149]
This is probably just something stupid on my end, but I can't see how to properly send commands like /hideads or /ad or properly set status as Looking in Bitlbee using the PURPLE_ONLY version of the plugin, or tasks like adding a friend or bookmark. Otherwise this works beautifully, and I really appreciate the effort keeping this up to day.

**Comment by vobe** [comment]
I quickly looked through the bitlbee code and I didn't find how you can make it run a libpurple command. Maybe someone else can answer you, but you might need to request that feature from the bitlbee devs

**Comment by Ceralor** [comment]
I'm not surprised to hear that, to be honest. I know there's an FB plugin
that adds its own root-channel commands from what I saw but that seems
unnecessary.
