### ISSUE TITLE
Not showing up in ubuntu 

### ISSUE THREAD

**Issue by Kradre** [fchat-pidgin/fchat-pidgin#151]
Have a Xubuntu 16.10 - fresh-installed. libjson-glib and pidgin-dev installed
When i was trying that plugin, pidgin didn't saw it. I put it in /usr/lib/purple-2 so it'd check it first.
Plus, turned on in pidgin debug output.
There's some part of log about plugin:

(14:33:46) plugins: /usr/lib/purple-2/flist_linux64_latest.so is not loadable: ABI version mismatch 2.11.x (need 2.10.x)

Version of libpurple is 2.10.12

**Comment by Kradre** [comment]
Found a problem - ubuntu repository not updating. (Keeping at 2.10.12)
Try to build pidgin from sources.

**Comment by Kradre** [comment]
http://sysads.co.uk/2016/06/21/pidgin-2-11-0-chat-app-released-install-on-ubuntu-16-04/
That instruction would work - tested already.

**Comment by vobe** [comment]
We don't really recommand rebuilding pidgin, instead you should just build the plugin so that it matches your version of pidgin.
