### ISSUE TITLE
With Spectrum 2, pidgin-fchat spams terminal with errors.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [fchat-pidgin/fchat-pidgin#155]
/usr/bin/spectrum2_libpurple_backend: symbol lookup error: /usr/lib64/purple-2/flist.so: undefined symbol: gtk_imhtml_class_register_protocol                                                           
/usr/bin/spectrum2_libpurple_backend: symbol lookup error: /usr/lib64/purple-2/flist.so: undefined symbol: gtk_imhtml_class_register_protocol                                                                                         
/usr/bin/spectrum2_libpurple_backend: symbol lookup error: /usr/lib64/purple-2/flist.so: undefined symbol: gtk_imhtml_class_register_protocol                                                                                         
/usr/bin/spectrum2_libpurple_backend: symbol lookup error: /usr/lib64/purple-2/flist.so: undefined symbol: gtk_imhtml_class_register_protocol

**Comment by vobe** [comment]
You need to compile the plugin with FLIST_PURPLE_ONLY=1, if that doesn't solve your issue, please show a complete compilation log including the command you're typing to compile the code
