### ISSUE TITLE
Failure to log in on Linux: SSL error

### ISSUE THREAD

**Issue by EdCaliburn** [fchat-pidgin/fchat-pidgin#156]
Hi,

For the past week or so, every time I've tried to log in through the F-Chat Pidgin plugin, I immediately get the following error.

Unable to connect to www.f-list.net: SSL Handshake Failed

The plugin works fine on Windows. I'm not sure if this is an issue with another package, but to the best of my knowledge, nothing has changed on my end. This didn't start happening immediately after a package update or anything like that, I checked specifically. I did update Pidgin and recompile with the latest version of the plugin to see if it would help, but it didn't. I also tried clearing my entire Pidgin configuration and starting over, with the same problem.

I am using Arch Linux and compiled the latest version of the plugin myself, with Pidgin and Purple 2.12.0. I'm happy to provide any logs that would help.

**Comment by vobe** [comment]
I would suggest trying to compile the plugin again with
```
make DISABLE_NSSFIX=1
```
(run `make clean` first to make sure you're really recompiling the plugin)

If this doesn't solve your issue, please provide your debug logs, you can see them by running `pidgin -d` on a command line or going to Pidgin's debug window. Don't forget to review those logs and make sure they do not contain your password

**Comment by revident** [comment]
Recompiled based on your suggested flag above. No difference.

Please note, asking for debug logs is a bad idea right now as Usernames and Passwords a printed in plain text in them. I've gone to an effort to scrub mine to be able to post it.

Platfrom is Fedora 25 with lastest updates.

**Comment by vobe** [comment]
```
(08:24:10) nss: Handshake failed  (-12286)
```
This corresponds to SSL_ERROR_NO_CYPHER_OVERLAP.
I think the version of NSS you are using is not compatible with the algorithms that www.f-list.net use for TLS. This would explain why it happens so suddently, my guess is that F-List changed their TLS configuration and your client is no longer compatible. I don't have an arch linux environment to test this on, but could you try the following command instead ?
```
tstclnt -h www.f-list.net -p 443 -o -D -v
```
This command will try to connect to the server using the SSL lib, and might tell us a bit more about what is going on on your system.

Also, make sure you are running the latest available version of the `nss` package on your arch system. It would probably be useful if you could tell me precisely which version you are using.

Finally, it might be useful to fiddle with the "NSS preferences" plugin for Pidgin, maybe try to force certain protocol versions (TLS 1.2 for instance) and see if you get better results.

**Comment by revident** [comment]
Package Version Installed.
```
$ rpm -q nss
nss-3.30.2-1.1.fc25.x86_64
```
Test command requested.
Line of Note: "Bad server certificate: -8179, Peer's Certificate issuer is not recognized."
```
$ /usr/lib64/nss/unsupported-tools/tstclnt -h www.f-list.net -p 443 -o -D -v
tstclnt: connecting to www.f-list.net:443 (address=104.24.10.70)
tstclnt: connect: PR_IN_PROGRESS_ERROR: Operation is still in progress (probably a non-blocking connect)
tstclnt: about to call PR_Poll for connect completion!
tstclnt: PR_Poll returned 0x02 for socket out_flags.
tstclnt: ready...
tstclnt: about to call PR_Poll !
tstclnt: PR_Poll returned!
tstclnt: PR_Poll returned 0x00 for stdin out_flags.
tstclnt: PR_Poll returned 0x01 for socket out_flags.
tstclnt: PR_Poll returned 0x01 for socket out_flags.
tstclnt: Read from server -1 bytes
tstclnt: about to call PR_Poll !
tstclnt: PR_Poll returned!
tstclnt: PR_Poll returned 0x00 for stdin out_flags.
tstclnt: PR_Poll returned 0x01 for socket out_flags.
tstclnt: PR_Poll returned 0x01 for socket out_flags.
tstclnt: using asynchronous certificate validation
tstclnt: Read from server -1 bytes
tstclnt: handshake was paused by auth certificate hook
Bad server certificate: -8179, Peer's Certificate issuer is not recognized.
tstclnt: SSL version 3.4 using 128-bit AES-GCM with 128-bit AEAD MAC
tstclnt: Server Auth: 256-bit TLS 1.3, Key Exchange: 255-bit TLS 1.3
         Compression: NULL, Extended Master Secret: Yes
subject DN: CN=ssl379398.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
issuer  DN: CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
0 cache hits; 0 cache misses, 0 cache not reusable
0 stateless resumes
Received 0 Cert Status items (OCSP stapled data)
tstclnt: about to call PR_Poll !
tstclnt: PR_Poll returned!
tstclnt: PR_Poll returned 0x00 for stdin out_flags.
tstclnt: PR_Poll returned 0x01 for socket out_flags.
tstclnt: PR_Poll returned 0x01 for socket out_flags.
tstclnt: Read from server -1 bytes
tstclnt: about to call PR_Poll !
tstclnt: PR_Poll returned!
tstclnt: PR_Poll returned 0x00 for stdin out_flags.
tstclnt: PR_Poll returned 0x01 for socket out_flags.
tstclnt: PR_Poll returned 0x01 for socket out_flags.
tstclnt: Read from server 0 bytes
tstclnt: about to call PR_Poll !
^C
```

**Comment by vobe** [comment]
The certificate error isn't relevant for this particular issue.

I was able to reproduce on arch, and the following steps solved the problem for me:
* Enable "NSS Preferences" plugin
* In the "NSS Preferences" plugin configuration screen, set "Maximum version" to TLS 1.2

This is probably an issue with the default algorithms used by Pidgin, I'll try to see if I can report it to them.

**Comment by EdCaliburn** [comment]
Looks like I got beaten to the punch on logs, but sounds like the issue has been nailed down. I can confirm the NSS Plugin workaround fixes the problem.

Thanks!

**Comment by vobe** [comment]
Glad to hear that this solved your problem, I've narrowed it down to an issue in the way TLS1.3 connexions are handled by either NSS or Cloudflare. I'll try to contact them, hopefully some more permanent solution can be worked out on their side

**Comment by SparklerPone** [comment]
That workaround won't work for bitlbee. Any ideas on any other options? Does NSS have a global config file that could be changed for this?

**Comment by vobe** [comment]
The nss-prefs plugin doesnt depend explicitely on pidgin so it would work but it would require you to copy over the relevant XML bits from pidgin config to bitlbee's libpurple config. Hardly a convenient way to bypass this issue. I'll look into extending our nss-hack component to handle this particular problem as well

**Comment by SparklerPone** [comment]
After talking to the bitlbee people, I was able to workaround this by downgrading nss to 3.28.1.

I did not have any luck with enabling libpurple plugins in bitlbee.

**Comment by vobe** [comment]
7b1dfb7 should fix the issue on all NSS versions, as long as you don't skip the NSS fix when compiling the plugin. Let me know if you get a chance to try it. Downgrading NSS isn't a very satisfying solution in the long run.

**Comment by SparklerPone** [comment]
Can confirm that that patch works with nss version 3.31.3(newest) in arch's repos. Thanks!

**Comment by vobe** [comment]
Opened an upstram ticket about this issue, let's see how it goes
https://developer.pidgin.im/ticket/17217

**Comment by dequis** [comment]
That's fixed with the merge of [this PR](https://bitbucket.org/pidgin/main/pull-requests/218/ssl-nss-use-default-nss-ciphersuites-tls/diff), will be in libpurple 2.12.1 (or 2.13.0)

You should probably add something like `#if !PURPLE_VERSION_CHECK(2, 12, 1)` to only use the hack in older versions. Or `purple_version_check(2, 12, 1) == NULL`, the runtime equivalent.

Thanks for bringing this to our attention.

**Comment by vobe** [comment]
Thanks for fixing this, I was secretely hoping for the solution you chose instead of just enabling more ciphers
