### ISSUE TITLE
logging in with BitlBee or Minbif fails with Syntax Error

### ISSUE THREAD

**Issue by JamesBarnes101** [fchat-pidgin/fchat-pidgin#163]
Hello,
Perhaps I am making a newbie mistake, but I am unable to use this plugin with either BitlBee or Minbif. I believe I have built the plugin correctly, because I am able to login just fine using Finch. However, every time I attempt to add my f-chat account in either BittleBee or Minbif, the process fails with a syntax error. For example in BitlBee, I'm doing the following:
"account add flist MyUsername MyPassword", and receiving the following output:
<root> flist - Logging in: Requesting login ticket
<root> flist - Logging in: Connecting to F-Chat server
<root> flist - Logging in: Sending WebSocket handshake
<root> flist - Logging in: Identifying
<root> flist - Login error: Syntax error.
<root> flist - Logging in: Signing off..

I know that my authentication attempt is at least partially successful, because if I use an incorrect username or password, I get different, relevant errors. I notice that I am not specifying a character name, but if there is a parameter I need to use in the "account add" command to pass that information, I'm not sure what it is. Any guidance would be muchappreciated.
Thanks!

**Comment by JamesBarnes101** [comment]
Thanks! What if the character name contains spaces?

**Comment by vobe** [comment]
Good point, and quick testing indicates it doesn't currently work. Bitlbee should probably write out a config file with the account information you send it. Possibly an accounts.xml file. If you edit this file (exit Bitlbee first) you should be able to put a proper space in there and it should connect correctly next time you run Bitlbee

I haven't run bitlbee in a while, I'll take a look at it by tomorrow

**Comment by vobe** [comment]
Well that was simple enough actually:
```
account add flist "myusername:mycharactername" mypassword
```
Using quotes did the trick for me. If it doesn't work for you, check `/var/lib/bitlbee/LOGIN.xml` for issues. The password in this file seem to be encrypted in some fashion, so don't worry if it doesn't seem to match your f-list account password.

**Comment by JamesBarnes101** [comment]
Awesome! Thank you!
