### ISSUE TITLE
New host address unresolvable

### ISSUE THREAD

**Issue by ThelsK** [fchat-pidgin/fchat-pidgin#164]
Newspost: https://www.f-list.net/newspost/330/

The server address changed to: wss://chat.f-list.net/chat2

Entering either 'chat.f-list.net/chat2' or 'wss://chat.f-list.net/chat2' results in an 'unknown host' error.

The server address change seems to be permanent, rendering the F-chat client unusable.

**Comment by vobe** [comment]
Indeed, the plugin was never meant to take a URL as parameter there. I'm reworking this and publishing a new release

**Comment by vobe** [comment]
Fixed with 0.7.0
