### ISSUE TITLE
Nightly build link broken

### ISSUE THREAD

**Issue by ThelsK** [fchat-pidgin/fchat-pidgin#165]
The link to the nightly build (at least the one listed in the #pidgin channel) is: http://beam.to/fchat-pidgin

However, beam.to stopped its services, rendering the link broken.

**Comment by TomTheDragon** [comment]
There you go --> https://voraffinity.de/zeug/pidgin/fchat-pidgin/

**Comment by vobe** [comment]
thanks @TomTheDragon

**Comment by ThelsK** [comment]
Nice! The link in the chat is updated, but the 0.7.0 installer still uses the beam.to address in the setup description. Perhaps it's best to update that during the next update?

**Comment by vobe** [comment]
I updated the docs with the new URL. Kinda surprised anyone reads the installer text;) thanks for reporting
