### ISSUE TITLE
Issues since 5/25 attack

### ISSUE THREAD

**Issue by Legan22** [fchat-pidgin/fchat-pidgin#166]
Unable to connect since 5/25/19 attack. Cannot login. Simply says connection has timed out. Attempts to use the new connection address listed on the main site results in an inability to connect.

**Comment by vobe** [comment]
Hi, you need to update to the latest version to be able to connect again:
https://github.com/fchat-pidgin/fchat-pidgin/releases/download/v0.7.0/fchat-pidgin-setup.exe

**Comment by Legan22** [comment]
Just downloaded and installed. No luck. Still popping up with the same "Connection timed out" error message. 

Address: chat.f-list.net

Does that not need to be changed in light of last night's attack?

**Comment by vobe** [comment]
With the new version you don't have anything to change (yet!) This error message probably means that the install did not work. You might have an old version of the plugin somewhere, look in your "program files" folder for any files named "flist.dll" or "libflist.dll", remove them, and install again.

After a successful install, the "advanced" tab in your F-List account options should contain an URL that starts with wss:

![image](https://user-images.githubusercontent.com/8561634/58385136-df2fba80-7feb-11e9-8698-34f13c5cafac.png)

**Comment by alexolog** [comment]
See #164

**Comment by Legan22** [comment]
Fixed it. Thanks!
