### ISSUE TITLE
Periodic "Connection timed out" disconnects

### ISSUE THREAD

**Issue by SomeAwfulFish** [fchat-pidgin/fchat-pidgin#167]
I grabbed the latest build this morning, and the client seems to connect fine. It syncs my lists and I am able to send and receive messages. However, each character I have on (regardless of how many are online) disconnects periodically, typically every 5 to 10 minutes. 

Here is what's shown in the debug window during one disconnection:

(20:46:14) connection: Connection error on 09B3FF60 (reason: 0 description: Connection timed out.)
(20:46:14) account: Disconnecting account Average:Toto (023FD420)
(20:46:14) connection: Disconnecting connection 09B3FF60
(20:46:14) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols\16\yahoo.png: Failed to open file 'C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols\16\yahoo.png': No such file or directory
(20:46:14) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols\16\discord.png: Failed to open file 'C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols\16\discord.png': No such file or directory
(20:46:14) g_log: flist_get_status_text: assertion `(fla = purple_connection_get_protocol_data(pc))' failed
(20:46:14) connection: Destroying connection 09B3FF60

**Comment by vobe** [comment]
F-Chat is very quick to disconnect if your connection is only a tiny bit unstable

You should see a "Sending message... (Code: PIN)" every minute or so, if you fail to send it  the server will disconnect you

**Comment by SomeAwfulFish** [comment]
I talked with Kira, who says the inactivity timeout is 2 minutes, but this time it disconnected 30 seconds after the most recent "Sending message... (Code: PIN)"

It seems to be sending it every 30 seconds, but then it will stop doing so. The relevant stuff happens at 8:48:32 (last CODE: PIN) and 8:49:01 (disconnect begins) in the log.
[purple-debug.log](https://github.com/fchat-pidgin/fchat-pidgin/files/3223811/purple-debug.log)

I also checked my ping to the server - it's under 40 ms.

**Comment by SomeAwfulFish** [comment]
It looks like the issue is probably my router. If not, it's my ISP, which would suck really bad. I've ruled out the problem being with the plugin, so I'm closing the issue. Thanks for your help.
