### ISSUE TITLE
Unable to join chats from Bitlbee-purple

### ISSUE THREAD

**Issue by Ceralor** [fchat-pidgin/fchat-pidgin#168]
As it says, I'm adding chats the same way i used to in order to join them, by name if official and by adh-ID if private, but I cannot join either. I get an error "Could not locate the requested channel" in the root window. Let me know anything else I can do to help.

**Comment by vobe** [comment]
This is how I would typically do it:

```
19:11 <@vobe> chat add flist Dragons
19:11 <@root> Chatroom successfully added.
19:11 <@vobe> chat add flist ADH-1509b63f1b1a98c79ab9
19:11 <@root> Chatroom successfully added.
19:12 <@vobe> channel list
19:12 <@root>  0. &bitlbee, control channel (joined)
19:12 <@root>  1. #Dragons, chat channel
19:12 <@root>  2. #ADH-1509b63f1b1a98c79ab9, chat channel
19:12 <@root> End of channel list
```
Then you can simply `/join #Dragons` and `/join #ADH-1509b63f1b1a98c79ab9`

If that doesn't work for you, you should try enabling some form of debugging in bitlebee and see if you get additionnal messages. But I'm afraid I don't know how to to that.

**Comment by Ceralor** [comment]
Not sure why it didn't work initially for me, but I followed your guide and it worked this time, using 'flist' instead of '0' for account ID. Thanks!
