### ISSUE TITLE
DISABLE_NSSFIX=1 should be the default for both Linux and Windows

### ISSUE THREAD

**Issue by Hypertyrannical** [fchat-pidgin/fchat-pidgin#171]
A lot of time has passed, just about everyone should be using the latest Pidgin or whatever else, and just about every network setup should be able to handle the new TLS standards. Hell, we're venturing into TLS 1.3 territory now.

I tested this boolean on Windows and have had no issues.

**Comment by vobe** [comment]
I agree that we should drop that fix in the next release. Tracking this in #131 already
