### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by alexolog** [fchat-pidgin/fchat-pidgin#174]
As of this morning, I am getting an error when trying to connect:

connection: Connection error on xxxxxxxxx (reason: 0 description: The server sent a WebSocket frame with an unknown opcode.)

The opcode itself is not logged so there is no way for me to tell if it is a legitimate problem or a bug.

**Comment by vobe** [comment]
Can't reproduce this over here.
This error usually means that the server you are connecting to does not even send a websocket frame at all, but some other kind of unexpected data. Check the server URL in your account options, the correct value is wss://chat.f-list.net/chat2 . If it's what you have, then maybe something's temporarily wrong with either your network or cloudflare. 
Also try without IPV6, just in case.

**Comment by alexolog** [comment]
It turned out to be a temporary server/network issue.  However, it would still be good to log unexpected responses.

**Comment by alexolog** [comment]
Can we get a Windows build please?

**Comment by vobe** [comment]
I have setup minimal CI for the project, you can find a build here :
https://github.com/fchat-pidgin/fchat-pidgin/suites/358494921/artifacts/692657

The corresponding Github UI isn't great at the moment, hopefully we can make nightly builds accessible without having to navigate too deep in the "Actions" section

**Comment by alexolog** [comment]
Thanks you!  Is it possible to make just the DLL available as well?

**Comment by vobe** [comment]
https://github.com/fchat-pidgin/fchat-pidgin/suites/359361105/artifacts/701364

**Comment by alexolog** [comment]
Thanks!
