### ISSUE TITLE
Error in version check

### ISSUE THREAD

**Issue by LurkerHub** [fchat-pidgin/fchat-pidgin#175]
Debug log:

```
(18:06:06) flist: Update Check JSON Received: { "version": { "full": "v0.7.0", "major": v0, "minor": 7, "bugfix": 0 }, "timestamp": "2019-05-26T14:46:14Z", "summary": "Updated F-Chat URL"}
(18:06:06) flist: Expected JSON Object, but did not parse with error message: <none>:1: Parse error: unexpected character `:', expected value
```

Happens consistently.

**Comment by vobe** [comment]
Indeed, the update JSON was incorrectly generated
Fixed at https://github.com/fchat-pidgin/version/commit/bd9e8b6b23a106c03d0f2d16187bf64cf069930a

Thanks

**Comment by alexolog** [comment]
Any plans on releasing a Windows DLL?
The nightly builds on https://voraffinity.de/zeug/pidgin/fchat-pidgin/ seem to have stopped on March 29

**Comment by vobe** [comment]
There is nothing to fix on the client side. It was a purely server-side (github) issue
