### ISSUE TITLE
[Feature Req] - Add message queue to respect server enforced 1 second delay

### ISSUE THREAD

**Issue by FalcoGer** [fchat-pidgin/fchat-pidgin#176]
When sending successive message you receive an error that the messages must be 1 second apart. It would be nice if the plugin handled that automatically, especially for buddy pounces.
This is especially handy for buddy pounces as you can only ever have one. If you send messages with the offline message emulation plugin, only one such message can be sent, even to different people, as when you log out and then come back, multiple of those people can be around, causing all messages to be sent at once.

A suggestion is to add a message queue to the account between sending off the message (from user/buddy pounce) and sending the network traffic and then have a status display for delayed messages in the output window of pidgin if the message had been delayed.

- nothing if it had been sent right away, read: the queue was empty and the last message timestamp was > 1s ago
- (delayed, pos N) if it is in the queue
- (sent at timestamp after delay of timespan) when sent

This might require asynchronous code, but I'd be happy if it works at all for now, meaning if pidgin stops responding while sending queued messages.

**Comment by vobe** [comment]
Duplicate of #114 I think. But a desirable feature indeed, definitely possible using https://docs.pidgin.im/pidgin/2.x.y/eventloop_8h.html

**Comment by FalcoGer** [comment]
Whoops. My bad.
