### ISSUE TITLE
Status (Cookie/Crown) Renders Buddies as Invisible

### ISSUE THREAD

**Issue by zephyrnok** [fchat-pidgin/fchat-pidgin#182]
Pidgin doesn't appear to recognize the status, and treats the status's user as if they are offline (though "get info" and messaging still works).  Status icon is displayed as the offline icon, and the user is hidden when "Hide Offline Buddies" is enabled in buddy list.  Status message also seems to be cleared from the Get Info field.

![2.0 vs Pidgin](https://user-images.githubusercontent.com/13741398/103925776-e1fdf700-50cc-11eb-85be-bfc04204a90c.png)

**Comment by vobe** [comment]
Indeed, the code did not register the Crown status to pidgin. Can you check if the latest commit fixes your issue? If you are running windows you can try this installer : https://github.com/fchat-pidgin/fchat-pidgin/suites/1788138464/artifacts/34216831

**Comment by zephyrnok** [comment]
Workin' on my build now, ace stuff 👍

(Installer for windows build was used)
