### ISSUE TITLE
Make the backround of ads configurable 

### ISSUE THREAD

**Issue by LurkerHub** [fchat-pidgin/fchat-pidgin#184]
The light green background makes some ads unreadable:

![image](https://user-images.githubusercontent.com/20542915/120027131-00538900-bfc1-11eb-91bf-23575d0a39ec.png)

Please make it configurable

**Comment by vobe** [comment]
Ad background color is already configurable: 
![image](https://user-images.githubusercontent.com/8561634/120062564-30ebff00-c063-11eb-99bc-898189d499d9.png)

**Comment by LurkerHub** [comment]
Thanks, missed that.
`#c0c0c0` works reasonably well
