### ISSUE TITLE
Allow for arbitrary scheme in --protocolhandler parameters

### ISSUE THREAD

**Issue by LurkerHub** [fchat-pidgin/fchat-pidgin#186]
As described in #145:

> please try the following build https://github.com/fchat-pidgin/fchat-pidgin/suites/2826019370/artifacts/62958668
> 
> In case of multiple accounts, the "first" one (whatever that means) will be joined to the desired channel. This is consistent with what other plugins do.
>
> > How do I pass the channel to pidgin with that build?
> 
> ```
> pidgin.exe --protocolhandler=https://www.f-list.net/fchat/?joinChannel=ADH-2b5c804cabc154006a57
> ```

Please remove the following check:
```
    // For now, only channel URLs are supported
    // eg https://www.f-list.net/fchat/?joinChannel=ADH-2b5c804cabc154006a57
	if (g_ascii_strcasecmp(proto, "https"))
		return FALSE;
```
Since registering `https` with pidgin is not an option, it prevents opening the link with pidgin simply by clicking it.
If you accept other protocols as well, it will be possible to rewrite the URL in the browser to a different scheme using an add-on or a user script.

**Comment by LurkerHub** [comment]
Pull request #189

**Comment by LurkerHub** [comment]
Updated

**Comment by LurkerHub** [comment]
Can you please make a Windows DLL with this?

**Comment by vobe** [comment]
https://github.com/fchat-pidgin/fchat-pidgin/actions/runs/987312322

**Comment by LurkerHub** [comment]
Thank you!
