### ISSUE TITLE
Characters should be colored according to their gender

### ISSUE THREAD

**Issue by fcwill** [fchat-pidgin/fchat-pidgin#29]
This feature already exists in code but doesn't really seem to work in reality, colors are pretty random for me.

Can someone confirm?

**Comment by fcwill** [comment]
Correction: This does not exist.
Will require some GTK hacking as a Pidgin-only feature.

**Comment by lutramustil** [comment]
I can confirm that the colours are random!

**Comment by fcwill** [comment]
This should work now (:tm:)
Minor drawback: The first message of a user in a channel will very likely have a wrong colored timestamp. Also, might affect performance a bit, especially in high traffic channels.

I'll leave this issue open for some feedback.
