### ISSUE TITLE
Removing buddies does not remove them from your friends list

### ISSUE THREAD

**Issue by fcwill** [fchat-pidgin/fchat-pidgin#56]
Removing a buddy from the buddy list in Pidgin does not remove them from you F-List friends list.

The function is located at f-list_commands.c (flist_pidgin_remove_buddy).

**Comment by syldrathecat** [comment]
It seems like adding people to your buddy list likewise doesn't add them to your F-List friends list. I'm not sure if one should happen without the other.

Likewise the ignore feature in Pidgin doesn't integrate with the server-side ignore feature at all.

**Comment by fcwill** [comment]
Adding buddies does add them to your F-List friends list (if you are using "Make friend request" from the buddy context menu).
Also, ignore stuff is integrated, as long as you use _/ignore add_ et al.
