### ISSUE TITLE
/priv command does not work

### ISSUE THREAD

**Issue by lutramustil** [fchat-pidgin/fchat-pidgin#64]
When trying to use the /priv command to open a private message, it returns a "Unknown command" error.

**Comment by lutramustil** [comment]
So this one seems to be hit or miss. I've had a few instances where it did not give me the private message, and I've had some names that do give them to me.

I don't know if this is an issue with extra spaces? I might just be finding bugs that aren't there, but thought it would at least be worth a mention.

**Comment by vobe** [comment]
After some quick testing it seems that spaces work in most cases, can you try to give me some examples of names with which it doesn't work ? Please also give the plugin version that you are using,, pidgin version and your operating system version

**Comment by lutramustil** [comment]
(7:41:07 AM) You are running Pidgin F-Chat 0.5.0 (v0.5.0-22-g743cc80).
On this computer, I'm running Windows 10.
I don't have any examples right at this moment. I'll see if I can find it in the logs or see if it does it for any other.

**Comment by fcwill** [comment]
I'll close this, since there hasn't been a comment in a long time and I can't reproduce this.
